### ISSUE TITLE
Clearance for counterbored side end bolts

### ISSUE THREAD

**Issue by thehans** [justinledwards/BigDelta#7]
I'm having difficulty getting the bolt heads to fit in the counterbored holes of the vertex piece.  It seems that there is no clearance designed into the part.  I've have to drill all my vertex parts out for the bolts to fit.

It looks like the holes in the part design are 9mm ID.  I printed parts at 0.25mm layer height, and the first bridged layer of the holes can sometimes sag a bit, which makes the hole effectively even smaller.

I have some of the ultra low profile openbuilds M5 bolts and they have 9.25mm diameter head.  I also have some M5 socket button head cap screw from McMaster and they are 9.5mm diameter.  I also checked a hex head cap screw which was 9mm at its widest.

Can the parts be changed so that the widest bolt head (9.5mm) will fit, and plus a few tenths of a mm for added clearance.  I think 10mm would be a nice round number.

**Comment by justinledwards** [comment]
@thehans 

I haven't talked to others yet, but it wouldn't be too difficult to turn those things into parameters.  Until something like that is done, I wanted to show where the sketch dimensions are at so you can modify them.  

![image](https://cloud.githubusercontent.com/assets/684524/22976282/23872d26-f358-11e6-86cb-2d766eefd7ac.png)

As these were designed early on in onshape, not all features were available yet and it could be cleaned up quite a bit.

**Comment by justinledwards** [comment]
I added a variable that you can adjust.

![image](https://cloud.githubusercontent.com/assets/684524/22999970/3e630a26-f3ac-11e6-9236-b149aed2ea26.png)
